name: PlayerMenu
main: cn.handyplus.menu.PlayerMenu
version: 1.7.5
author: handy
api-version: 1.13
website: https://ricedoc.handyplus.cn/wiki/PlayerMenu/log/
softdepend: [ PlaceholderAPI,Vault,PlayerPoints,PlayerGuild,PlayerCurrency,LEconomy,CMI ]
description: 玩家菜单插件
folia-supported: true
commands:
  playerMenu:
    description: 玩家菜单插件
    aliases: [ plm ]
permissions:
  playerMenu.*:
    description: 玩家菜单插件
    children:
      playerMenu.reload: true
      playerMenu.create: true
      playerMenu.view: true
      playerMenu.getMaterial: true
      playerMenu.adminOpen: true
      playerMenu.open: true
      playerMenu.close: true
      playerMenu.clock: true
      playerMenu.clear: true
      playerMenu.getItem: true
      playerMenu.addItem: true
      playerMenu.convert: true
  playerMenu.reload:
    description: 重新加载配置
    default: op
  playerMenu.create:
    description: 创建
    default: op
  playerMenu.view:
    description: 管理员进行查看信息
    default: op
  playerMenu.getMaterial:
    description: 获取材质
    default: op
  playerMenu.adminOpen:
    description: 打开
    default: op
  playerMenu.open:
    description: 打开
    default: true
  playerMenu.close:
    description: 关闭
    default: true
  playerMenu.clock:
    description: 给玩家配置的菜单
    default: true
  playerMenu.clear:
    description: 清理数据
    default: op
  playerMenu.getItem:
    description: 获取菜单物品
    default: op
  playerMenu.addItem:
    description: 新增菜单物品
    default: op
  playerMenu.convert:
    description: 转化数据库
    default: op