name: PlayerMenu
main: cn.handyplus.menu.PlayerMenu
version: 1.5.0
author: handy
api-version: 1.13
website: https://ricedoc.handyplus.cn/wiki/PlayerMenu/log/
softdepend: [ PlaceholderAPI,Vault,PlayerPoints,PlayerGuild,PlayerCurrency ]
description: 玩家菜单插件
folia-supported: true
commands:
  playerMenu:
    description: 玩家菜单插件
    aliases: [ plm ]
permissions:
  playerMenu.*:
    description: 玩家菜单插件
    children:
      playerMenu.reload: true
      playerMenu.create: true
      playerMenu.view: true
      playerMenu.getMaterial: true
      playerMenu.adminOpen: true
      playerMenu.open: true
      playerMenu.close: true
  playerMenu.reload:
    description: 重新加载配置
    default: op
  playerMenu.create:
    description: 创建
    default: op
  playerMenu.view:
    description: 管理员进行查看信息
    default: op
  playerMenu.getMaterial:
    description: 获取材质
    default: op
  playerMenu.adminOpen:
    description: 打开
    default: op
  playerMenu.open:
    description: 打开
    default: true
  playerMenu.close:
    description: 关闭
    default: true